"""empty message

Revision ID: 13510d028236
Revises: a1d44139acd1
Create Date: 2022-08-15 15:01:47.157361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13510d028236'
down_revision = 'a1d44139acd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
